---
abstract: 'A tool to build C libraries.'
author:
  - 'Alberto Simoes <ambs@cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0.23'
  File::Spec: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4208, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-LibBuilder
provides:
  ExtUtils::LibBuilder:
    file: lib/ExtUtils/LibBuilder.pm
    version: '0.05'
resources:
  license: http://dev.perl.org/licenses/
version: '0.05'
